export const APPLY_SEARCH_PARAMETERS = 'APPLY_SEARCH_PARAMETERS'
export const CLEAR_SEARCH_PARAMETERS = 'CLEAR_SEARCH_PARAMETERS'


// Users Actions
export const ACQUIRE_INITIAL_TOKEN = 'ACQUIRE_INITIAL_TOKEN'
export const ACQUIRE_INITIAL_TOKEN_SUCCESS = 'ACQUIRE_INITIAL_TOKEN_SUCCESS'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_ERROR = 'USER_ERROR'

// UI Actions
export const OPEN_GLOBAL_MODAL = 'OPEN_GLOBAL_MODAL'
export const OPEN_GLOBAL_MODAL_SUCCESS = 'OPEN_GLOBAL_MODAL_SUCCESS'
export const CLOSE_GLOBAL_MODAL = 'CLOSE_GLOBAL_MODAL'

// Review Actions
export const ADD_REVIEW = 'ADD_REVIEW'
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS'

export const TARGET_BUILDING = 'TARGET_BUILDING'
