export const APPLY_SEARCH_PARAMETERS = 'APPLY_SEARCH_PARAMETERS'
export const CLEAR_SEARCH_PARAMETERS = 'CLEAR_SEARCH_PARAMETERS'

export const UPDATE_TEMP_PARAMS = 'UPDATE_TEMP_PARAMS'
export const UPDATE_PARAMS = 'UPDATE_PARAMS'
export const DISCARD_TEMP_PARAMS = 'DISCARD_TEMP_PARAMS'
