export const APPLY_SEARCH_PARAMETERS = 'APPLY_SEARCH_PARAMETERS'
export const CLEAR_SEARCH_PARAMETERS = 'CLEAR_SEARCH_PARAMETERS'


// Users Actions
export const ACQUIRE_INITIAL_TOKEN = 'ACQUIRE_INITIAL_TOKEN'
export const ACQUIRE_INITIAL_TOKEN_SUCCESS = 'ACQUIRE_INITIAL_TOKEN_SUCCESS'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_ERROR = 'USER_ERROR'
